export const ADD_PICTURE = "ADD_PICTURE";
export const SET_NEW_TITLE = "SET_NEW_TITLE";
export const SET_NEW_URL = "SET_NEW_URL";
export const LOAD_PICTURES = "LOAD_PICTURES";
export const FETCH_PICTURES = "FETCH_PICTURES";
export const FETCH_PICTURES_SUCCESS = "FETCH_PICTURES_SUCCESS";
export const FETCH_PICTURES_ERROR = "FETCH_PICTURES_ERROR";
